### ISSUE TITLE
Hi! The lib is giving some error ;) [interceptable-http.js:6Uncaught ReferenceError: __extends is not defined]

### ISSUE THREAD

**Issue by barbatchov** [gund/ng2-http-interceptor#93] opened 2016-12-27 11:16 UTC
interceptable-http.js:6Uncaught ReferenceError: __extends is not defined
    at interceptable-http.js:6
    at Object.<anonymous> (interceptable-http.js:19)
    at __webpack_require__ (bootstrap 01c23fe…:52)
    at Object.<anonymous> (main.bundle.js:53937)
    at __webpack_require__ (bootstrap 01c23fe…:52)
    at Object.<anonymous> (main.bundle.js:74782)
    at __webpack_require__ (bootstrap 01c23fe…:52)
    at Object.<anonymous> (main.bundle.js:74739)
    at __webpack_require__ (bootstrap 01c23fe…:52)
    at Object.<anonymous> (main.bundle.js:53991)

**Comment by gund** [comment] 2016-12-27 11:26
Duplicate of #89

**Closed by gund** 2016-12-27 11:26 UTC
